version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Maven dependencies"
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  build:
    commands:
      - echo "Building the application..."
      - mvn clean package -DskipTests

artifacts:
  files:
    - target/*.jar
    - target/*.war
    - Procfile
    - .ebextensions/**/*
  discard-paths: yes
