version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo "Running Maven package..."
      - mvn clean package -DskipTests

artifacts:
  files:
    - target/*.war
  discard-paths: yes
