version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - mvn clean package -DskipTests
      - mv target/*.war ROOT.war
artifacts:
  files:
    - ROOT.war
  discard-paths: yes
